### ISSUE TITLE
Clicking Harvest doesnt work in windowed mode

### ISSUE THREAD

**Issue by Rainson12** [Barragek0/ClickIt#12]
You reverted my changes in your commit https://github.com/Barragek0/ClickIt/commit/d5b433b763094efe56b23edc5f9dcd2845e7b28a#diff-d9d1576daf268462f2b7a704a947eafb819c5499c467305c5ee9f6da5f604107L1097
which reintroduced the issue of not being able to auto click the harvest laben when being in windowed mode as the calculation of the x and y position is ignoring the window position.

**Comment by Barragek0** [comment]
Sorry, reverted it as I thought this was causing an issue with clicking items, but that was a seperate issue. Re-adding this to everything in the next version soon.
