### ISSUE TITLE
Downside 100 problem.

### ISSUE THREAD

**Issue by illidank** [Barragek0/ClickIt#2]
Can you make the tool does not turn up green when downside is at 100? There's some build breaking mods, but in this case both option gave this mod, and the tool will pick the one with more upside :( hence still breaking the map for some build. 
If we still need to read the green square to check every time, it negate the use of the tool itself 
![123](https://user-images.githubusercontent.com/7278592/209441935-a44b4646-6338-45f3-8713-54c49a759e82.png)

**Comment by Barragek0** [comment]
Will add this in the next version, thanks for the feedback.

**Comment by illidank** [comment]
Thanks for great work man.
