### ISSUE TITLE
Searing Exarch Player Downside Mod Weight linked together

### ISSUE THREAD

**Issue by Kiritocs** [Barragek0/ClickIt#3]
![image](https://user-images.githubusercontent.com/81497153/209448885-181d01b2-830f-4a7b-a514-f0e4d834ad7d.png)

using Version v3.20.1.2

**Comment by Barragek0** [comment]
Fixed in v3.20.1.3

**Comment by 69GamingC** [comment]
![image](https://user-images.githubusercontent.com/105999830/210741294-7374fe82-c412-4975-9629-ea177efc8f50.png)
same happen with two of this mods.
