### ISSUE TITLE
Vaal and Annulment orb are tied together in settings

### ISSUE THREAD

**Issue by MeTeC-FR** [Barragek0/ClickIt#4]
Hello, there is a little issue when tweaking the values of Searing Exarch (Eldritch Minions) for the Vaal and Annulment Orbs, both are tied together when trying to set the weight on them.

If you could fix this that would be wonderful. 

Thank you very much for your work, your additions for this plugin are completely awesome.

**Comment by Barragek0** [comment]
Fixed by commit #8a1b22d
