### ISSUE TITLE
hi I feel grateful for your development

### ISSUE THREAD

**Issue by chunhyowoon** [Barragek0/ClickIt#9]
I also want to make various things but I don't know how to do it from the beginning. Can I ask you personal questions about how to compile in visual studio code and these basic things through Discord?

**Comment by Barragek0** [comment]
I barely know anything when it comes to c# so there's not much I could teach you. I started this plugin to learn c#. There's tons of resources online, and even free courses you can take to learn c#, I just used this project as im a more hands on learner, and I learn much better through trial and error, which is how I taught myself most other languages, AHK, python, java.

**Comment by chunhyowoon** [comment]
Thank you for your answer. I've made macros for the Python or ahk part, so I know the basics. I'll learn more and try one plug-in. Thank you
